# Generated by Django 3.1.7 on 2021-07-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('홈데코/조명', '홈데코/조명'), ('패브릭', '패브릭'), ('가구', '가구'), ('가전', '가전'), ('수납/정리', '수납/정리'), ('DIY/공구', 'DIY/공구')], max_length=20),
        ),
    ]
